version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: deploy/Dockerfile-frontend
    ports:
      - 443:443
    volumes:
      - ${CERTS_PATH}:/etc/certs/:ro

  backend:
    build:
      context: .
      dockerfile: deploy/Dockerfile-backend
    volumes:
      - ${OCI_CONF_PATH}:/app/oci/:ro
