FROM python:3.10-slim

WORKDIR /app
COPY server .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["gunicorn", \
            "--bind=8080", \
            "--worker-class=aiohttp.GunicornWebWorker", \
            "app:build_app"]
