FROM ghcr.io/graalvm/nodejs:22 AS ui

WORKDIR /ui
COPY ui .
RUN npx shadow-cljs release ui

FROM nginx:1.23-alpine

COPY --from=ui /ui/public /usr/share/nginx/html
COPY deploy/nginx.conf /etc/nginx/nginx.conf
